# Generated by Django 6.1.1 on 2026-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Когда было последнее напоминание"
            ),
        ),
    ]
